version: 2

sources:
  - name: snowflake_sample_data
    schema: TPCH_SF1
    tables: 
      - name: customer_source
        identifier: customer
      - name: order_source
        identifier: orders